# 관리자 권한 찾기
sudo: required

# 언어 선택 
language: generic

# docker 환경에서 실행
services:
  - docker

# Script 를 적용하기 위한 환경 설정 
before_install:
  - echo "도커 파일 생성이 시작됩니다."
  - docker build -t soldiersung/react-app -f Dockerfile.dev .

# 실행할 Script 작성 
script:
  - docker run -e CI=true soldiersung/react-app npm run test -- --coverage


#############  배포  ############# 
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-187582693911"
  bucket_path: "docker-react-app"
  on:
    # master branch 에 push 가 될 때에만 배포
    branch: master
    
  # Access Key 설정 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY

   
