version: '3'
services:
  # container 이름 -> react 
  react:
    # docker file 사용 
    build: 
      # context : docker 이미지를 구성하기 위한 파일과 폴더들이 있는 위치 
      # dockerfile 과 같은 위치에 있기 때문에 다음과 같이 표시 
      context:  . 
      # dockerfile : docker 파일이 무엇인지 명시
      dockerfile: Dockerfile.dev
    # port : portMapping  => localPort : Container Port
    ports:
      - '80:3000'
    
    # local Machine 에 있는 파일들 Mapping 
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    
    # stdin_open: react 한정 -> 버그를 없애주기 위함
    stdin_open: true
  
# Container 하나 더 추가 --------------------------------------------------------


  # Container 추가 -> 자유롭게 해도 된다 
  test-test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    # TEST 를 수행할 명령어 추가 
    command: ["npm","run","test"]



